"""Add decision column to cases

Revision ID: 0af0b32a65ff
Revises: adf6639cfbdf
Create Date: 2025-02-18 15:41:10.067305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0af0b32a65ff'
down_revision: Union[str, None] = 'adf6639cfbdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
