"""Added created_at to Case model

Revision ID: 162e22164813
Revises: 4e8b006296aa
Create Date: 2025-02-03 17:48:37.436672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '162e22164813'
down_revision = '4e8b006296aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
