"""Add created_at to Norm model

Revision ID: 495121e4562f
Revises: 1b80b825c65f
Create Date: 2025-02-10 17:52:02.669095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '495121e4562f'
down_revision: Union[str, None] = '1b80b825c65f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('norms', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('norms', 'created_at')
    # ### end Alembic commands ###
