"""Fix status column with default value

Revision ID: 4e8b006296aa
Revises: 284043fc9eb9
Create Date: 2025-02-02 19:19:42.221980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e8b006296aa'
down_revision = '284043fc9eb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), server_default='pending', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
