"""Add decision column to cases

Revision ID: 28c323783217
Revises: 495121e4562f
Create Date: 2025-02-10 19:03:37.786123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28c323783217'
down_revision: Union[str, None] = '495121e4562f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('decision', sa.Enum('ACCEPTED', 'REJECTED', name='decision_enum'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cases', 'decision')
    # ### end Alembic commands ###
